Add some lowlevel accessor functions
vishalkuo/bimap pull request #1
Opened 2017-11-10 21:05 UTC by martin31821

It was not possible to retrieve the underlying maps of the bimap e.g. to iterate
over the keys or the values.

I added some getters for the forward and inverse maps as well as Lock and Unlock functions.
I have to mention that those functions are low level and should only be used to read values.

2017-11-10 21:11 UTC, vishalkuo commented
Thanks for the contribution @martin31821! I know that the implementations are pretty trivial for the accessors but could we possibly write simple unit tests for them? I.e. create a bimap and assert that we get back the correct forward and inverse maps are returned? 

I only ask because if the underlying implementation ever changes in the future we'd be able to catch issues with it.

2017-11-10 21:45 UTC, martin31821 commented
I never done unit tests in go before, but I'll try and update the PR

2017-11-10 22:02 UTC, vishalkuo commented
Thanks for attempting! Take a look at [bimap_test.go](https://github.com/vishalkuo/bimap/blob/master/bimap_test.go) for reference!

2018-01-01 15:50 UTC, vishalkuo requested changes
Bump on this PR, would you still like to merge this functionality in? If so, would you be ok with adding some tests?

2018-01-02 13:39 UTC, martin31821 commented
I added some tests for GetForwardMap and GetInverseMap.
I couldn't find a way to assert some actions block within the test framework, so I couldn't add a test for Lock/Unlock.

2018-01-02 17:07 UTC, vishalkuo approved these changes

2018-01-02 17:08 UTC, merged

2018-01-02 17:08 UTC, vishalkuo commented
Thanks for your contribution!